package se.wmuth.openc25k.data

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * Keeps the data for an entire running session
 *
 * @param name the name of the run e.g. Week 1 Day 1
 * @param description the description of the run, any extra info the user needs
 * @param isComplete whether the user has completed this run
 * @param intervals an array of intervals which the run consists of
 * @constructor creates a running session containing all needed info
 */
@Parcelize
data class Run(
    val name: String,
    val description: String,
    var isComplete: Boolean,
    val intervals: Array<Interval>
) : Parcelable {
    // Autogenerated comparison functions
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Run

        if (name != other.name) return false
        if (description != other.description) return false
        if (isComplete != other.isComplete) return false
        if (!intervals.contentEquals(other.intervals)) return false

        return true
    }

    override fun hashCode(): Int {
        var result = name.hashCode()
        result = 31 * result + description.hashCode()
        result = 31 * result + isComplete.hashCode()
        result = 31 * result + intervals.contentHashCode()
        return result
    }
}